apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: PUT_IMAGE_HERE
          ports:
            - containerPort: 5173
          end:
            - name: VITE_API_URL
              value: http://backend:8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: blog
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
